-- Cheaty.nvim

vim.pack.add({ "https://github.com/stikypiston/cheaty.nvim" })

require("cheaty").setup({
	cheatsheet = {
		"# Cheatsheet",
		"",
		"## Basics",
		"- gq         : Wrap to 80-character long lines",
		"- : [visual] : do the '<,'> thing",
		"- g??        : ROT13 the current line for some reason",
		"- <leader>r  : :%s/",
		"- ~          : Toggle case of character under cursor",
		"",
		"## Marks",
		"- m[letter]  : Create mark of that letter",
		"- m,         : Create next available mark",
		"- '[letter]  : Go to mark of that letter",
		"- m<         : Go to previous mark",
		"- m>         : Go to next mark",
		"- m.         : Go to last-edited line",
		"- :delmark x : Delete mark of that letter",
		"",
		"## NeoWiki",
		"- <leader>ow : Open NeoWiki",
		"- <leader>oW : Open floating NeoWiki",
		"- <leader>ms : Open Mindmap of current file",
		"- <BS>       : Go back to previous file",
		"",
		"## Studytools",
		"- <leader>sp : Start Pomodoro timer (25/5 minute intervals)",
		"- <leader>sP : Pomodoro timer status",
		"- <leader>sb : Start blurting buffer",
		"",
		"### Inline Annotations",
		"- !IMPORTANT!",
		"- !QUESTION!",
		"- !STUDY!",
		"- !DEFINITION!",
		"- !EXAMPLE!",
		"- !REVIEW!",
		"- !MEMORISE!",
		"- !CUSTOM[Custom]!",
		"",
		"## Folding",
		"- zc         : Fold",
		"- zM         : Fold all",
		"- zo         : Unfold",
		"- zO         : Unfold all under cursor",
		"- zr         : Unfold all one level",
		"- zf         : Create fold",
		"- za         : Toggle fold under cursor",
		"",
		"## Surrounds",
		"- sa         : Add surround",
		"- sd         : Delete surround",
		"- sr         : Replace surround",
		"- sf         : Find surround (forward)",
		"- sF         : Find surround (backward)",
		"",
		"## LSP",
		"- <leader>ld : Trouble diagnostics",
		"",
		"## Terminal",
		"- <leader>ot : Open terminal split"
	}
})
